stages:
  split_data:
    cmd: python3 src/stages/split_data.py
    deps: 
    - src/stages/split_data.py
    - data/raw/Churn_Modelling.csv
    params:
    - base
    - data
    - data_split
    outs:
    - data/processed/x_train.csv
    - data/processed/x_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
  train: 
    cmd: python3 src/stages/train.py
    deps: 
    - src/stages/train.py
    - data/processed/x_train.csv
    - data/processed/y_train.csv
    params:
    - data
    - data_split
    - train
    outs:
    - models/model.pkl
  eval:
    cmd: python3 src/stages/evaluate.py
    deps:
    - src/stages/evaluate.py
    - models/model.pkl
    - data/processed/x_test.csv
    - data/processed/y_test.csv
    metrics:
    - reports/metrics.json:
        cache: false 
    plots:
    - reports/confusion_matrix.png:
        cache: false




